### ISSUE TITLE
Open review form

### ISSUE THREAD

**Issue by tsdh** [FTSRG/trainbenchmark-ttc#10]
Hi guys,

I've already written you via easychair last week but got no reply so far.  So here I am again to tell you that I'm still waiting for your open review form link so that I can link it from the TTC website and people can start scoring the Train Benchmark solutions.

Thanks,
Tassilo

**Comment by szarnyasg** [comment]
Hi!

Sorry for the delay, I created the form now and it is available here: https://docs.google.com/forms/d/1mU7Ym8Y7U6Ymr6k-2-RIkdzmOYNsed4hLmKBeLYNYOY/viewform. Let me now if you find anything that needs to be fixed.

Gabor

**Comment by tsdh** [comment]
Thanks!  It's fine as it is.  I've linked it now from the TTC solutions page.
