### ISSUE TITLE
OR (ATL/EMFVTM): SemaphoreNeighbor pattern

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/trainbenchmark-ttc#11]
Hi, 

I'm reading your submission (http://www.transformation-tool-contest.eu/solutions/train/TTC_2015_submission_16.pdf) and noticed that you used `route3` for the SemaphoreNeighbor query. The submitted case description contained a slightly different pattern, but we decided to change it before while finalizing case description (https://github.com/FTSRG/trainbenchmark-ttc-paper/commit/52f1d9f645a55d6401bf66c4c2446711739a67a5).

Is there any reason you used the `route3` node in the graph pattern?

Gabor

**Comment by szarnyasg** [comment]
@dwagelaar

**Comment by dwagelaar** [comment]
Oh dear, I got that from the paper at
https://github.com/FTSRG/trainbenchmark-ttc/tree/master/paper, but it must
have been an old revision. Says on
http://www.transformation-tool-contest.eu/cfs.html that the tasks may
change up to April 2nd, so I did not check back after that.
Should I update the solution?

Dennis

**Comment by szarnyasg** [comment]
Yes, please update it so I can run the benchmark on the updated version (also update the paper if possible). I think the implementating this change should be fairly straightforward.

Thanks,
Gabor

**Comment by szarnyasg** [comment]
As a related note, I find the implementation of the RouteSensor query a bit hard to comprehend. Why is the `routesWithSensors` helper attribute required? While it would not make a difference with the current model, I think the pattern should return the `{Route, SwitchPosition, Switch, Sensor}` tuples, where the `(Route)-[follows]->(SwitchPosition)-[switch]->(Switch)-[sensor]->(Sensor)` edges are present, but the Route does not have a `definedBy` edge. Of course, this Route does not confirm the metamodel so a simple validation would reveal it as well, but
1) I think this would make the OCL code simpler,
2) there are no performance penalties,
3) it matches the RouteSensor pattern.

What do you think?

**Comment by dwagelaar** [comment]
I don't think the helpers are required, for both SwitchSet and RouteSensor.
I will test with the helpers removed.

**Comment by tsdh** [comment]
With respect to updating, of course that's fine.  The problem however is that the SHARE image is already published and thus immutable.  Given that it's not really your fault because the case description changed over time, I'm fine if you prepare a completely new image, but of course that means a bit additional work for you.  (I'd suggest you ask Pieter van Gorp (the SHARE master, @pvgorp here at github) first.  Maybe there's a way to make an already published image mutable again, but I know that has been impossible in the past.)

**Comment by pvgorp** [comment]
Easiest solution: clone the previous image

**Comment by tsdh** [comment]
Oh, well, that's indeed a nobrainer.

**Comment by tsdh** [comment]
Ah, now I remember why that didn't come to my mind. In the past, I've always hosed my first and second images in such a way that they wouldn't boot anymore, and thus I always had to start from scratch. Usually, I got it right with the third try.

This year, just one try. I really improved with increased age! :-)

**Comment by pvgorp** [comment]
Progress :)

**Comment by dwagelaar** [comment]
I've pushed all changes to github, and I'm now finalising the new SHARE image.

**Comment by pvgorp** [comment]
Share demo is online from now onwards

**Comment by dwagelaar** [comment]
Thanks! URL is
http://is.ieis.tue.nl/staff/pvgorp/share/?page=ConfigureNewSession&vdi=ArchLinux64-TTC15_TTC15_ATL_ATL.vdi

Dennis

**Comment by tsdh** [comment]
I'll update the link at the TTC site tomorrow or on Monday morning at the latest.

**Comment by szarnyasg** [comment]
I checked the updated paper. The ATL query is fine but the textual description was not updated:

```
The SemaphoreNeighbor task consists of a query that checks for Routes r1 that have an exit Semaphore,
and a Sensor s1 connected to another Sensor s2 – defining another Route r3 – by two TrackElements
te1 and te2, for which there is no other Route r2 that connects the same Semaphore and the other
Sensor s2. Furthermore, a repair transformation is provided, which removes the exit Semaphore from
Route r1.
```

**Comment by dwagelaar** [comment]
Indeed, I missed that one paragraph, thanks! I will update it, and submit a
new version of the paper.

**Comment by dwagelaar** [comment]
Paper updated on EasyChair (and github).

**Comment by szarnyasg** [comment]
Thanks!
