### ISSUE TITLE
[NMF] Running solution on SHARE

### ISSUE THREAD

**Issue by tsdh** [FTSRG/trainbenchmark-ttc#14]
Hi Lucia & Georg,

how do I run the solution on SHARE?

I've tried `./bin/Release/TrainBenchmarkMono.exe --runIndex 1 --size 256 --query SemaphoreNeighbor --changeSet fixed --iterationCount 10` but then I get errors because it doesn't find a file `--runIndex` (what's the run index, btw?) or `--size` and other weird things.  Hey, those are command line options not files, no?

Also, I cannot start monodevelop for which a start shell script exists on the desktop.  Executing that just says `Cannot open assembly: ./monodevelop/lib/monodevelop/bin/MonoDevelop.exe': Not a directory`.
Ah, it's just the leading dot.  Executing `/monodevelop/lib/monodevelop/bin/MonoDevelop.exe` works.

Ok, so now I have monodevelop up and running.  I've rebuilt all projects which worked fine.  But still I cannot execute the solution.  Doing Run > Run with > mono 3.x.y when the Program.cs of the train benchmark case is open results in a FileNotFoundException because the `--runIndex` file couldn't be found, i.e., the same kind of error I get on the command line.

Hm, I also cannot find some README, so please help me.

**Comment by georghinkel** [comment]
Hi,

sorry for the late response, I am currently in holidays :)

There actually is a README right on the Desktop, I have just changed the Readme that's been there and refitted it to the NMF solution. When I saw other solutions creating their own readmes and leaving the one that has been there unchanged, I was alrady afraid that peopl would not notice...

The problem running the NMF solution is that under Linux, .NET assemblies cannot be run directly as Linux does not know how to do that. For this reason, you have to run the solution using mono ...

Furthermore, for some reason I only noticed after publishing, the first command line parameter must be the path to the model that should be loaded. There is a modified version of run.py that runs the benchmark correctly.

Hope that helps,

Georg

**Comment by tsdh** [comment]
Ok, now I got it running.  I'm still curious what the `--runIndex` option means.

**Comment by szarnyasg** [comment]
@tsdh the `--runIndex` option is deprecated. An earlier version of the Train Benchmark TTC case ran the benchmarks in separate JVMs and used this option to pass the index of the current run (so the `runIndex` took a value from 1...5). Now that all runs happen in the same JVM, we no longer use this option.

**Comment by georghinkel** [comment]
Hi Gabor,

I did not recognize the framework was changed this way. My solution still uses the parameter, but it is a straight-forward thing to create a for-loop around the core benchmarked code

Georg

**Comment by tsdh** [comment]
Ok, thanks. For testing it is enough for me to run your solution once per query, so I think it doesn't matter what I provide with that option, right?

**Comment by georghinkel** [comment]
Well, the option is actually being used for writing the output, so you should enter a number and this number is then used for the appropraiet field in the output tsv.

**Comment by tsdh** [comment]
Yes, I noticed that I can't omit that. :-)

**Comment by szarnyasg** [comment]
@georghinkel, can you please implement this change, i.e. run drop the `runIndex` argument and run the benchmark 5 times in the same process?
Also, can you please provide a README file on how to build the solution?

**Comment by georghinkel** [comment]
@szarnyasg, yes I can and I will implement this change, i.e. change it to a --runs parameter where you can specify how many runs are required. 

Regarding the README, there already is a readme file on the SHARE demo that explains how the code is structured and how to compile it using Mono conveniently from within monodevelop, at least if you try often enough as Mono for whatever reason sometimes fails the build (I usually needed three attempts).

For running the code on CoreCLR, there is a bit more work involved since according to https://github.com/Microsoft/msbuild/issues/58, CoreCLR does not yet support MSBuild and this is not currently worked on. Therefore, I will have to use this Json-based mini build engine that comes with the CoreCLR and which is hardly documented at the moment.
