### ISSUE TITLE
OR [EMF-IncQuery]: What's the meaning of ^?

### ISSUE THREAD

**Issue by tsdh** [FTSRG/trainbenchmark-ttc#15]
In listing 1, there's `SwitchPosition.^switch(switchPosition, sw)`.  What's the meaning of the `^` here?

BTW, your listing references are wrong.  You reference listing 1 as listing 5 in the text and listing 2 is referenced as listing 6.

**Comment by istvanrath** [comment]
The `^` is used for escaping, as `switch` is a reserved keyword in Java. This is needed because of technical reasons as IQPL is bound to the Java type system through Xbase, the language we use inside `check` expressions.

**Comment by tsdh** [comment]
But ^ is also a java operator, so you or Xbase must do some internal escaping anyhow. And then you or Xbase could automatically check for java keywords just as well without imposing that on users, no?

**Comment by istvanrath** [comment]
If you think this is worth the effort then feel free to file a Bugzilla entry on this topic for the IncQuery product on bugs.eclipse.org. If I remember correctly this boils down to an Xbase/Xtext issue so it's likely we'll just pass it on to them.
