### ISSUE TITLE
OR [FunnyQT] Match Comparison

### ISSUE THREAD

**Issue by fikovnik** [FTSRG/trainbenchmark-ttc#18]
I was wondering what is the reason of having a HO function `make-match-comparator` and then using it to create 5 different comparators instead of having one generic comparator which can be used to compare tuples of arbitrary size?

**Comment by szarnyasg** [comment]
@fikovnik: IIRC we discussed during the TTC session with @tsdh and the conclusion was that the solution could be shortened by two lines of code :).

**Comment by tsdh** [comment]
I was wrong. The matches need to be compared in some fixed order, so this is really needed.
