### ISSUE TITLE
Request for slightly different comparators

### ISSUE THREAD

**Issue by tsdh** [FTSRG/trainbenchmark-ttc#2]
The comparators requested in the case description compare all elements in a match one-by-one.  However, my FunnyQT solution only matches the elements which are actually modified later on.  This enables a more efficient matching strategy in FunnyQT, so I'd much prefer to stick to that solution as it is the one I'd recommend if one is looking for best performance.

I've implemented a comparator which is like the one suggested in the paper except that it only compares the elements of the matches which are later modified in the repair transformation.  If no distinction could be made based on these elements, the comparator throws an exception.  No such exceptions are triggered when running the benchmarks, so I conclude that it is sufficient to compare only the elements going to be modified in order to compute a unambiguous total order upon the matches.

So I'd be happy if we could change the case description accordingly.

**Comment by szarnyasg** [comment]
Hi!

Sorry for taking so long to respond. Can you please clarify the part about "my FunnyQT solution only matches the elements which are actually modified later on"?
Accordint to the specification of the benchmark, the benchmark needs to return all matches of the pattern and the match comparator is only used to create an ordered list of the matches.

Gabor

**Comment by tsdh** [comment]
Yes, I return all matches of the patterns but the matches of some patterns contain less elements than required by the comparators.

Take RouteSensor as an example.  The match is defined in the paper as `<route, sensor, swP, sw>`.  But the repair action only needs the `route` and the `sensor` in order to link them.  Therefore, the RouteSensor-matches of my solution only contain the `route` and the `sensor`.  Of course, it is ensured that there is a path from the `route` to the `sensor` as defined by the pattern but the intermediate SwitchPosition and Switch aren't captured as part of the matches.

**Comment by tsdh** [comment]
PING :-)

**Comment by szarnyasg** [comment]
Hi!

After some discussion with my colleagues we concluded that we require the tools to return **all elements** in the match.
I think the vast majority of the tools can return both `<route, sensor, swP, sw>` and `<route, sensor>` for the RouteSensor query. Returning the whole match is more realistic as 1) it should help the user in identifying the problem 2) there may be multiple meaningful repair operations (affecting different model elements) on a match.

Gabor

**Comment by tsdh** [comment]
Ok, too bad. :-(
