### ISSUE TITLE
Compile errors after importing into Eclipse

### ISSUE THREAD

**Issue by tsdh** [FTSRG/trainbenchmark-ttc#3]
`scripts/run.py -b` finishes with SUCCESS, but when I import the current HEAD into Eclipse, I get several compile errors:
1. `EMFBenchmarkCase.java` calls `bc.getInstanceModelPath()` and `bc.getSize()` where `bc` is a `BenchmarkConfig` declared in `AbstractBenchmarkCase`, but the methods `getInstanceModelPath()` and `getSize()` are undefined for `BenchmarkConfig`.
2. Same errors in `BenchmarkResult.java` in the `generateRow()` method.

I did `git reset --hard origin/master` to ensure that this is not caused by some of my local modifications.

**Comment by szarnyasg** [comment]
I did a rename to prevent the users from confusing the `TrainBenchmarkConfig` and the `BenchmarkConfig` classes: https://github.com/FTSRG/trainbenchmark-ttc/commit/c4f2a291c168058f9ab5a4e5f8d12a8f45935b50
Did you also pull the latest version from this repository?

The `getInstanceModelPath()` and the `getSize()` methods are defined in the [`GenericConfig`](https://github.com/FTSRG/trainbenchmark-ttc/blob/master/hu.bme.mit.trainbenchmark.ttc.benchmark/src/main/java/hu/bme/mit/trainbenchmark/ttc/config/GenericConfig.java) file.

**Comment by tsdh** [comment]
@szarnyasg Yes, that's the HEAD commit now.  And indeed `BenchmarkConfig` extends `GenericConfig` which does indeed define these methods...

Ah, I can "fix" the errors by modifying the files (e.g., adding a whitespace and removing it again) and then saving.  So it's some eclipse hiccup.  Sorry for the noise.
