### ISSUE TITLE
SHARE image provides 1 GB RAM, but assignment mentions 4 GB

### ISSUE THREAD

**Issue by dwagelaar** [FTSRG/trainbenchmark-ttc#6]
The SHARE image I got for TTC15 provides 1 GB of RAM. However, the assignment paper mentions a Linux x86 system with 4 GB of RAM. What do I provide in my config.json:
1. In my git repo? (N.B. runs on Travis against 3 GB of RAM)
2. In my SHARE image?

**Comment by szarnyasg** [comment]
@dwagelaar, thanks for reporting this, I did not notice this so far.
1. I think this value does not really matter as long as it is not too large (which may cause systems low on memory to slow down / freeze). The reviewer who clones your repository or anyone looking to run a benchmark will redefine this according to her environment.
2. 512M is a good choice (that would be the default as well: "Default Maximum Heap Sizes: [...] 50% of available physical memory up to 2 GB" as stated by https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html)

**Comment by dwagelaar** [comment]
Thanks! That works for the SHARE image.
